#Jekyll configuration
name: Farng Hwai Public Website 2020
description: Farng Hwai Public Website 2020 initial try
url: "https://farnghwai.github.io/"
theme: jekyll-theme-cayman
markdown: kramdown
kramdown:
  input: GFM
